Added directory and file exclusion, updated whitelist
ROCm-Developer-Tools/HIPIFY pull request #181
Opened 2020-09-02 14:54 UTC by bjoo

-exclude-dirs="dirlist"  will set up list of direcotries to be excluded
 -exclide-files="filelist" will set up a list of files to be excluded

List separator is the ',' (comma) like for whitespaces

2020-09-03 11:16 UTC, emankov requested changes
LGTM, otherwise formatting in the generated perl code.

2020-09-03 15:12 UTC, bjoo commented on src/CUDA2HIP_Perl.cpp
> +    *streamPtr.get() << tab_2 <<  print << "\" Skipping  excluded file: $fileName \\n\";" << endl_tab << "}";
Added

2020-09-03 15:12 UTC, bjoo commented
Requests completed.

2020-09-03 15:15 UTC, emankov approved these changes
Thank you!

2020-09-03 15:16 UTC, merged

2026-03-18 13:40 UTC, bjoo commented
Hi @emankov . Since I have changed employment from ORNL to industry, I probably am not able to contribute to ROCm anymore.  Please reassign this.

2026-03-18 14:08 UTC, emankov commented
> Hi @emankov . Since I have changed employment from ORNL to industry, I probably am not able to contribute to ROCm anymore. Please reassign this.

No problem, my friend. Thank you for all your previous contributions!