[HIPIFY] Address sanitizer support
ROCm-Developer-Tools/HIPIFY pull request #315
Opened 2021-04-12 21:51 UTC by aakanksha555

SWDEV-269088 - [ROCm Feature Address Sanitizer Support] address sanitizer needs to be enabled in hipify-clang build

2021-04-13 06:56 UTC, emankov requested changes
Why you need the AddressSanitizer unconditionally?
What if ADDRESS_SANITIZER is false?
Have you run the tests? They all are failed (at least on Windows).

2021-04-15 21:54 UTC, aakanksha555 commented
>Why you need the AddressSanitizer unconditionally?
> What if ADDRESS_SANITIZER is false?
Got it, I'll add an else bit.

> Have you run the tests? They all are failed (at least on Windows).
Would it be possible for you to share an error log you see on Windows?

2021-04-15 22:03 UTC, emankov commented
> Would it be possible for you to share an error log you see on Windows?

It is because of missing `else` and as a result - missing `-std=c++`

2021-04-15 22:12 UTC, emankov commented
Where does `ADDRESS_SANITIZER` define come from?
And I'd prefer that it will be switched off in Release.

2021-04-29 15:57 UTC, aakanksha555 commented
> Where does `ADDRESS_SANITIZER` define come from?
> And I'd prefer that it will be switched off in Release.

The ADDRESS_SANITIZER option may be specified as a cmake option to enable/ disable address sanitizer; it will be disabled by default unless explicitly enabled using the cmake option "-DADDRESS_SANITIZER=ON".
With ADDRESS_SANITIZER enabled all tests are failing with "ERROR: AddressSanitizer: use-after-poison .." error, potentially exposing memory leaks. We currently do not have the tests enabled in our internal CI so it won't cause an issue even if this patch is pushed through; but this should definitely be looked into.

2021-04-30 10:05 UTC, emankov requested changes

2021-04-30 10:05 UTC, emankov commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${EXTRA_CFLAGS} -fsanitize=${addr_var}")
`-fsanitize=` is useless if not erroneous in case of not `ADDRESS_SANITIZER`.

2021-05-04 20:14 UTC, emankov requested changes
Building after cmake with `-DADDRESS_SANITIZER=1` leads to the following error on Windows:

```
dist\include\llvm/Support/Compiler.h(434,11): fatal error C1083: Cannot open include file: 'sanitizer/asan_interface.h': No such file or directory
```
Additional include path to LLVM sanitizer should be specified for building hipify-clang.
In LLVM sources `asan_interface.h` lives here `llvm-project\compiler-rt\include\sanitizer\`.

Please, also check if compiler-rt should be built as well. Currently, only clang is needed for building hipify-clang besides llvm. If some `compiler-rt` libs are needed during building hipify-clang with `-fsanitize=address`, then the include path should be specified to `asan_interface.h` from `dist` folder, not `llvm-project`.

Finally, README should be updated accordingly.

2021-05-18 16:15 UTC, aakanksha555 commented
> Building after cmake with `-DADDRESS_SANITIZER=1` leads to the following error on Windows:
> 
> ```
> dist\include\llvm/Support/Compiler.h(434,11): fatal error C1083: Cannot open include file: 'sanitizer/asan_interface.h': No such file or directory
> ```
> 
> Additional include path to LLVM sanitizer should be specified for building hipify-clang.
> In LLVM sources `asan_interface.h` lives here `llvm-project\compiler-rt\include\sanitizer\`.
> 
> Please, also check if compiler-rt should be built as well. Currently, only clang is needed for building hipify-clang besides llvm. If some `compiler-rt` libs are needed during building hipify-clang with `-fsanitize=address`, then the include path should be specified to `asan_interface.h` from `dist` folder, not `llvm-project`.
> 
> Finally, README should be updated accordingly.

I think I always had my llvm built with compiler-rt so I hadn't seen this error before. But, I verified the error by building HIPIFY with llvm built with and without compiler-rt. Including compiler-rt when building llvm does the trick.

2021-05-18 17:28 UTC, emankov commented
What about this (at least on Windows):

> Additional include path to LLVM sanitizer should be specified for building hipify-clang.

And what about libs, do we need to specify the lib(s) as well while building `hipify-clang`?

2021-05-18 19:18 UTC, aakanksha555 commented
I don't have a windows setup. Would it be possible for you to provide some assistance with that?
Currently, without any additional paths, what do you see if you try to build on Windows?

2021-05-18 20:00 UTC, emankov commented
> I don't have a windows setup. Would it be possible for you to provide some assistance with that?
> Currently, without any additional paths, what do you see if you try to build on Windows?

Please, see the compilation error above.

2021-05-18 20:47 UTC, emankov commented
> > > I don't have a windows setup. Would it be possible for you to provide some assistance with that?
> > > Currently, without any additional paths, what do you see if you try to build on Windows?
> > 
> > 
> > Please, see the compilation error above.
> 
> Even after you build/install compiler-rt with llvm? On linux, hipify picks it up from the dist folder at "llvm-project/dist/lib/clang/13.0.0/include/sanitizer/asan_interface.h"

I need time to check. Anyway, by making changes in the build system, you should be able to check the build on all supported platforms. There is a detailed instruction in [Readme.md](https://github.com/ROCm-Developer-Tools/HIPIFY#readme) on how to build and test on Windows.

2021-05-19 10:39 UTC, emankov approved these changes
`asan_interface.h` is found if `compiler-rt` is specified when building `LLVM` on Windows. hipify-clang build with `-DADDRESS_SANITIZER=1` on Windows is correct now, all tests passed.

So, the change LGTM.

2021-05-19 10:43 UTC, merged